### ISSUE TITLE
Parsing U+10000 or above in username produces unexpected result

### ISSUE THREAD

**Issue by sideshowbarker** [smola/galimatias#51]
Test case: http://💩:foo@example.com
(U+1F4A9 in username)

Results from galimatias:

```
$ java -cp dependencies/galimatias-0.2.1.jar:dependencies/icu4j-53_1.jar io.mola.galimatias.cli.CLI http://💩:foo@example.com
Base: http://example.org/foo/bar
Analyzing URL: http://💩:foo@example.com
Parsing...
    Recoverable error found;
        Error: Illegal character in user or password: not a URL code point
        Position: 13
    Result:
        URL: http://%F0%9F%92%A9%3F:fo@example.com/
        URL type: hierarchical
        Scheme: http
        Scheme data: 
        Username: %F0%9F%92%A9%3F
        Password: fo
        Host: example.com
        Port: 80
        Path: /
Canonicalizing with RFC 3986 rules...
    Result identical to WHATWG rules
Canonicalizing with RFC 2396 rules...
    Result identical to RFC 3986 rules
```

Notice that is shows `%F0%9F%92%A9%3F` as the result for the username part, while it should just be `%F0%9F%92%A9`, and it shows `fo` instead of `foo` as the result for the password part.

I get expected results with code points in username less than U+FFFF; e.g., ￮ (U+FFEE).
But with U+10000 and higher, e.g., 𐀠 (U+10020), I get the same unexpected behavior as above.

**Comment by smola** [comment]
Thanks! I have rewritten most of the code related to iterating codepoint for the upcoming 0.3.0 release (which is currently broken for a few cases). I'll test this case with it.

**Comment by sideshowbarker** [comment]
It seems like this is actually a regression caused by my PR #46.

**Comment by sideshowbarker** [comment]
This is now fixed on master and a ParseIssueTest test case for it was added in 6696412
