### ISSUE TITLE
Can't parse Youtube's URLs

### ISSUE THREAD

**Issue by alexott** [smola/galimatias#62]
It reports error "A label contains hyphen-minus ('-') in the third and fourth positions." when parsing the youtube URLs like:

https://r7---sn-h557snes.googlevideo.com/videoplayback?c=web&clen=22485380&cpn=C3rgExh48LQwERuV&ctier=L&cver=as3&dur=314.800&expire=1464901020&fexp=9405186%2C9405978%2C9408209%2C9410705%2C9416126%2C9416891%2C9422596%2C9423965%2C9424336%2C9426977%2C9427547%2C9428398%2C9431012%2C9432369%2C9432684%2C9432895%2C9433096%2C9433380%2C9433655%2C9433801%2C9433946%2C9434244%2C9435527%2C9435876%2C9436110%2C9436797%2C9437067%2C9437090%2C9437553%2C9437669%2C9437722%2C9437773%2C9437981&gir=yes&id=d0e640b1c07dea77&initcwndbps=6761250&ip=103.245.47.20&ipbits=0&itag=135&keepalive=yes&key=yt6&lmt=1458182387695722&mime=video%2Fmp4&mm=31&mn=sn-h557snes&ms=au&mt=1464879076&mv=m&nh=IgpwcjAyLm1hYTAzKgkxMjcuMC4wLjE&pl=23&range=7419425-8716287&ratebypass=yes&requiressl=yes&signature=855D9BAC604149EE8CE5067A0FA9FAD0A736ABB2.094BDC4D52B494E9D48994373BFF88465C0932CB&source=youtube&sparams=clen%2Cctier%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&sver=3&upn=f_6bvtUkBXU

**Comment by smola** [comment]
Fixed in https://github.com/smola/galimatias/pull/69
